/**
 * Claude AI content generation service.
 *
 * Mode priority:
 *   1. Claude CLI (claude -p ...) — user logged in via `claude` terminal session, no API key needed
 *   2. Anthropic SDK — if ANTHROPIC_API_KEY is set in .env
 *
 * Content is generated by combining all brand context files + generation rules + spreadsheet row data
 * into a single comprehensive prompt.
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const crossSpawn = require('cross-spawn');

// Lazy-load queueService to avoid circular deps — only needed at call time
function getActiveModel() {
  try { return require('./queueService').getClaudeModel(); } catch { /* fallback */ }
  return process.env.CLAUDE_MODEL || 'claude-sonnet-4-6';
}

function getActiveEffort() {
  try { return require('./queueService').getClaudeEffort(); } catch { /* fallback */ }
  return 'high';
}

// Active generation engine: 'native' (built-in 2-call pipeline) or 'seomachine'
// (drives seomachine's methodology + Python quality gate). queue_state wins if it
// exposes the setting (UI-toggleable later); otherwise falls back to env, then 'native'.
function getActiveEngine() {
  try {
    const q = require('./queueService');
    if (typeof q.getGenerationEngine === 'function') {
      const e = q.getGenerationEngine();
      if (e) return String(e).toLowerCase();
    }
  } catch { /* fallback */ }
  return (process.env.GENERATION_ENGINE || 'native').toLowerCase();
}

// cross-spawn resolves the `claude` command to its real binary on every platform
// (on Windows the global install is a `claude.cmd`/`claude.ps1` shim that Node's
// child_process.execFile/spawn cannot launch directly — it throws ENOENT). It also
// escapes arguments safely, so user-supplied prompts cannot inject shell commands.
const spawn = crossSpawn;

/**
 * Promise wrapper around the Claude CLI that mimics the parts of execFileAsync we use.
 * Buffers stdout/stderr, supports a timeout, and rejects on non-zero exit or spawn error.
 * @returns {Promise<{stdout: string, stderr: string}>}
 */
function execClaudeAsync(args, opts = {}) {
  const { timeout, ...spawnOpts } = opts;
  return new Promise((resolve, reject) => {
    const proc = crossSpawn('claude', args, {
      env: { ...process.env, NO_COLOR: '1' },
      ...spawnOpts,
    });

    let stdout = '';
    let stderr = '';
    let settled = false;

    const finish = (fn, arg) => {
      if (settled) return;
      settled = true;
      if (timer) clearTimeout(timer);
      fn(arg);
    };

    // On Windows the spawned process is a `cmd.exe`/shim that forks the real
    // `claude` (node) process; proc.kill() only reaps the shim and leaves the
    // child alive (pipes stay open, 'close' never fires). taskkill /T kills the
    // whole tree. On POSIX a plain kill is sufficient.
    const killTree = () => {
      if (!proc.pid) return;
      if (process.platform === 'win32') {
        crossSpawn('taskkill', ['/pid', String(proc.pid), '/T', '/F']);
      } else {
        proc.kill('SIGKILL');
      }
    };

    const timer = timeout
      ? setTimeout(() => {
          killTree();
          finish(reject, new Error(`Claude CLI timed out after ${timeout}ms`));
        }, timeout)
      : null;

    proc.stdout?.on('data', (chunk) => { stdout += chunk.toString(); });
    proc.stderr?.on('data', (chunk) => { stderr += chunk.toString(); });

    proc.on('error', (err) => finish(reject, err));

    proc.on('close', (code) => {
      if (code === 0) return finish(resolve, { stdout, stderr });
      finish(reject, new Error(stderr.trim() || `Claude CLI exited with code ${code}`));
    });
  });
}

// Cache CLI status for 1 minute — short enough that a fresh login shows up quickly
let _cliCache = null;
let _cliCacheTime = 0;
const CLI_CACHE_TTL = 60 * 1000;

// Lazy-load the Anthropic SDK only when API key mode is needed
let _sdkClient = null;
function getSdkClient() {
  if (!_sdkClient) {
    const Anthropic = require('@anthropic-ai/sdk');
    _sdkClient = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  }
  return _sdkClient;
}

// ─────────────────────────────────────────────────────────────
// Context & rules loading
// ─────────────────────────────────────────────────────────────

function loadContextFiles(contextPath) {
  if (!contextPath) return '';
  const absPath = path.resolve(process.cwd(), contextPath);
  if (!fs.existsSync(absPath)) return '';
  const files = fs.readdirSync(absPath).filter(f => f.endsWith('.md')).sort();
  return files.map(f => {
    const content = fs.readFileSync(path.join(absPath, f), 'utf8');
    return `### Context File: ${f}\n${content}`;
  }).join('\n\n---\n\n');
}

function loadRulesFile(rulesPath) {
  if (!rulesPath) return '';
  const absPath = path.resolve(process.cwd(), rulesPath);
  if (!fs.existsSync(absPath)) return '';
  return fs.readFileSync(absPath, 'utf8');
}

// ─────────────────────────────────────────────────────────────
// Prompt construction
// ─────────────────────────────────────────────────────────────

function buildFeedbackSection(feedbackList) {
  if (!Array.isArray(feedbackList) || !feedbackList.length) return '';
  const items = feedbackList.map((f, i) => {
    const tag = f.rating === 'down' ? ' [fix — this was a problem]'
      : f.rating === 'up' ? ' [keep doing this]' : '';
    return `${i + 1}. ${String(f.feedback).trim()}${tag}`;
  }).join('\n');
  return `## Editor Feedback — Apply These Learnings (HIGHEST PRIORITY)
The human editor reviewed previously published drafts for this blog and left the notes below. Treat them as strict, non-negotiable requirements and apply EVERY one of them to this article. If any conflict with the general rules above, the editor feedback wins.
${items}
`;
}

// Derive the brand name from a blog config row: "EveryCRED Blog" -> "EveryCRED".
function brandFromBlog(blog) {
  const raw = blog && blog.name ? String(blog.name).trim() : '';
  const name = raw.replace(/\s*blog\s*$/i, '').trim();
  return name || (blog && blog.domain) || 'this brand';
}

function buildSystemContent(contextContent, rulesContent, feedbackList = [], blog = {}) {
  const brand = brandFromBlog(blog);
  return `You are a senior content strategist and blog writer for ${brand}. You write expert-level, SEO-optimized blog articles that read like they come from a practitioner with years of real, hands-on experience — not a generic content writer.

## Writing Identity
- Write in first person as a senior practitioner at ${brand}
- Ground every claim in the real proof points, case studies, outcomes, and capabilities given in the Brand and Editorial Context below — never invent metrics, and never borrow another company's case studies or numbers
- Confident and direct — never hedge with "might", "possibly", "could potentially"
- Plain language over jargon; explain technical concepts clearly

## How to Use the Rules and Context Below
The Brand and Editorial Context and the Generation Rules that follow are AUTHORITATIVE for this specific blog. They define its brand voice, audience, word count, FAQ count, heading style, formatting, banned phrases, internal-linking sources, and structure. Wherever they specify a number or a rule, follow THEM — never substitute a generic default. If anything elsewhere in this prompt conflicts with them, the blog's rules win.

${contextContent ? `## Brand and Editorial Context\n\n${contextContent}` : ''}
${rulesContent ? `## Generation Rules\n\n${rulesContent}` : ''}
${buildFeedbackSection(feedbackList)}
## Generation Process — Follow These Phases in Order

### Phase 1 — RESEARCH
Before writing, model the SERP landscape:
- What do the top-ranking articles for this keyword all cover? What is MISSING?
- What unique angle can ${brand} own that competitors don't, based on the brand context above?
- What is the exact search intent: informational, commercial, transactional?
- What People Also Ask questions exist? Build them into H2s or FAQ.
- Where do the brand's real proof points (from the context above) add genuine evidence? Never invent or borrow numbers.
- Check the internal-links-map context file for already-published ${brand} articles on similar topics — link to them for internal linking, and do NOT write a duplicate of an article that already exists.

### Phase 2 — WRITE
Follow this exact structure:
1. **Direct answer first** (1-2 sentences): AI scrapers (ChatGPT, Perplexity, Gemini) pull from the top of the page. Answer the query IMMEDIATELY.
2. **Hook** (choose one: provocative question / surprising stat / bold statement / counterintuitive claim)
3. **APP formula**: Agree (acknowledge reader's belief) → Promise (what they'll learn) → Preview (mini-TOC for long posts)
4. **Body** (H2 sections with H3 sub-sections — use the section count and per-section length from this blog's rules): Every claim backed by logic or data. No filler.
5. **Conclusion**: Summarize key takeaways
6. **CTA**: Natural call to action relevant to ${brand}
7. **FAQ**: Use the FAQ count and answer length defined in this blog's rules

### Phase 3 — OPTIMIZE (Rank Math 80-100 checklist — satisfy EVERY item)
This is mandatory. The article is scored by Rank Math SEO; hit all of these:

**Focus keyword placement (use the EXACT primary keyword phrase, verbatim):**
- In the FIRST sentence of the article (within the first 10% of content)
- In the H1 / title
- In AT LEAST 2 of the H2 subheadings, written as the exact phrase
- Use the EXACT primary keyword phrase 8-12 times across the article (intro, at least 2 H2s, several body paragraphs, the conclusion) — Rank Math measures density on the exact phrase, so 4-6 uses scores too low; aim for ~1% without sounding stuffed
- In the image alt text
- In the URL slug
- In the SEO title and meta description

**SEO title (\`seo_title\`):** 50-60 characters. START with the primary keyword. Include ONE number (a year, count, or stat) AND ONE power word (e.g. Proven, Essential, Complete, Ultimate, Smart, Powerful). Make it positive or clearly definitive in sentiment.

**Meta description (\`meta_description\`):** 150-160 characters. Include the primary keyword within the first 120 characters. End with a soft call to action.

**URL slug (\`slug\`):** lowercase, hyphen-separated, 3-6 words, MUST contain the primary keyword, ≤ 75 characters, no stop-word padding.

**Links (required for score — DISTRIBUTE, never cluster):**
- Internal links from the internal-links-map context file (use the internal-link count from this blog's rules), each placed in a DIFFERENT section where the topic is contextually relevant — never list them all in one paragraph or at the end
- AT LEAST 1 external link to a high-authority source (e.g. a well-known industry/research/standards site), placed inline within the paragraph that cites the stat or claim it supports — not in a standalone "sources" section
- No section should contain more than 1-2 links; spread them naturally across the body

**Structure & readability:**
- Hit the word count, section count, and FAQ count defined in this blog's Generation Rules — do not pad or fall back to a generic length
- Short paragraphs (per the blog's rules), at least one bulleted or numbered list, and a "Key Takeaways" bulleted block near the top
- Schema-friendly FAQ (clean Q&A pairs)

### Phase 4 — SCRUB
Before finalizing, remove AI fingerprints and apply this blog's formatting and banned-phrase rules:
- Apply this blog's punctuation and formatting rules exactly (em dashes, heading punctuation, etc.) as defined in its Generation Rules
- Remove banned filler: "it's worth noting", "in today's landscape", "in conclusion", "delve into", "leverage", "utilize", plus any others the blog's rules ban
- Vary sentence length (mix short punchy sentences with longer explanatory ones)
- Remove any zero-width spaces or invisible Unicode characters
- Ensure no paragraph starts with "I" consecutively

## CALL-TO-ACTION (CTA) BLOCKS
Produce exactly 3 distinct CTAs that drive business and generate qualified leads for ${brand}, tailored to THIS article's topic.
- Tone: professional, expert, confident, approachable, and high-conversion (a direct sales tone that asks for the next step).
- Voice: write like a human, not AI. Use simple present tense and strong action verbs. Be concise.
- Each CTA needs: a punchy heading (≤ 60 chars), a 1-2 sentence description (≤ 160 chars) tied to the reader's outcome, and a short button label (2-5 words, action verb, e.g. "Talk to a Cloud Expert", "Get Your Free Assessment").
- The 3 CTAs must be unique (different angle/offer), not repetitive.
- Also classify the article into ONE cta_category from this exact list (pick the closest fit): "ai", "cloud", "digital_transformation", "data", "technology_consulting", "digital_experience", or "default" if none clearly fits.

## CRITICAL OUTPUT FORMAT
You MUST respond with ONLY a single valid JSON object. No markdown fences, no commentary, no text before or after. The exact format:
{"title":"<H1 / post title, includes primary keyword>","seo_title":"<50-60 char SEO title, starts with primary keyword, has a number + a power word>","slug":"<keyword-rich-url-slug>","meta_description":"<150-160 chars, primary keyword in first 120 chars>","content":"<full HTML>","image_prompt":"...","image_alt":"<short alt text that includes the primary keyword>","tags":["..."],"faq":[{"question":"...","answer":"..."}],"cta_category":"<ai|cloud|digital_transformation|data|technology_consulting|digital_experience|default>","ctas":[{"heading":"...","description":"...","button":"..."},{"heading":"...","description":"...","button":"..."},{"heading":"...","description":"...","button":"..."}]}`;
}

function buildOutlinePrompt(row) {
  const secondaryKw = Array.isArray(row.secondary_keywords) ? row.secondary_keywords.join(', ') : (row.secondary_keywords || '');
  return `Before writing the full article, produce a research-backed outline.

Article Topic: ${row.title}
Primary Keyword: ${row.primary_keyword}
Secondary Keywords: ${secondaryKw}
Blog Type: ${row.blog_type || 'Article'}
ICP: ${row.icp || ''}
Pain Points: ${row.pain_points || ''}
Search Intent: ${row.intent || 'Informational'}

Respond with ONLY a JSON object:
{"unique_angle":"<what makes this article different from top 10 competitors — 1 sentence>","direct_answer":"<first 1-2 sentences that directly answer the query>","h2_sections":[{"heading":"<H2 text>","key_points":["<point>","<point>"],"has_mini_story":true,"internal_link":{"anchor":"<descriptive anchor text>","url":"<url from internal-links-map>"},"external_link":{"anchor":"<descriptive anchor>","url":"<authoritative external URL>"}}],"faq":[{"question":"<question>","answer":"<15-20 word answer>"}],"meta_description":"<150-160 chars including primary keyword>"}

Rules:
- 4-7 H2 sections. 2-3 sections should have has_mini_story:true.
- Assign 1 internal_link to each of 3-5 different sections (from the internal-links-map). Each section gets at most ONE internal link. Do NOT put the same link in multiple sections.
- Assign 1 external_link to exactly 1-2 sections where a stat or claim needs an authoritative source. Leave external_link null for sections that don't need one.
- FAQ items: match the count required by this blog's generation rules (typically 4-6).`;
}

function buildUserPrompt(row, outline = null, additionalInstructions = '', blog = {}) {
  const brand = brandFromBlog(blog);
  const secondaryKw = Array.isArray(row.secondary_keywords)
    ? row.secondary_keywords.join(', ')
    : (row.secondary_keywords || '');

  const outlineSection = outline ? `
RESEARCH OUTLINE (use this as your writing blueprint):
Unique Angle: ${outline.unique_angle || ''}
Direct Answer (use as opening): ${outline.direct_answer || ''}
Planned H2 Sections:
${(outline.h2_sections || []).map((s, i) => {
  const iLink = s.internal_link ? `\n     → Internal link: anchor="${s.internal_link.anchor}" url=${s.internal_link.url}` : '';
  const eLink = s.external_link ? `\n     → External link: anchor="${s.external_link.anchor}" url=${s.external_link.url}` : '';
  return `  ${i+1}. ${s.heading}${s.has_mini_story ? ' [include mini-story]' : ''}
     Key points: ${(s.key_points||[]).join('; ')}${iLink}${eLink}`;
}).join('\n')}
Pre-approved FAQ: ${JSON.stringify(outline.faq || [])}
Meta Description: ${outline.meta_description || ''}

LINK PLACEMENT RULE: Each link listed above must appear inline within that section's prose, anchored to a naturally fitting phrase. Do NOT collect links at the end of a section or in a dedicated "Resources" paragraph. Every link lives inside a sentence that flows without the link.

Follow this outline exactly. Expand each section to 250-400 words.
` : '';

  return `Generate a complete blog article for these details:
${outlineSection}
Title: ${row.title}
Primary Keyword: ${row.primary_keyword}
Secondary Keywords: ${secondaryKw}
Blog Type: ${row.blog_type || 'Article'}
Theme: ${row.theme || 'Technology'}
Target Industry: ${row.target_industry || ''}
Funnel Stage: ${row.funnel_stage || 'BOFU'}
Search Intent: ${row.intent || 'Informational'}
Audience (ICP): ${row.icp || ''}
What They Need: ${row.icp_solutions || ''}
Pain Points: ${row.pain_points || ''}
Desired Outcome: ${row.outcome || ''}
SEO Strategy: ${row.seo_strategy || ''}
AEO Strategy: ${row.aeo_strategy || ''}
CTR Hook: ${row.ctr_strategy || ''}
Target Locations: ${row.target_location || ''} (target discreetly — do NOT mention these locations explicitly)
AEO+GEO Notes: ${row.aeo_geo_strategy || ''}

${additionalInstructions ? `\nADDITIONAL INSTRUCTIONS FROM EDITOR (highest priority — apply these on top of all other rules):\n${additionalInstructions}\n` : ''}Instructions:
- Research this topic thoroughly and write a solid, comprehensive article at the word count specified in this blog's generation rules
- Use the internal-links-map context file for internal linking (use the link count from this blog's rules). Place each link in a DIFFERENT section, anchored inline to a naturally fitting phrase — never group multiple links in the same paragraph or in a standalone "Resources" section at the end
- Add at least ONE external link to a high-authority source, placed inline within the paragraph that cites the stat or claim it supports
- Follow all brand voice, style, and SEO guidelines from context files
- Use the EXACT primary keyword "${row.primary_keyword}" in: the first sentence, the H1, at least 2 H2 headings, the image alt, the slug, the seo_title, and the meta description
- Use the EXACT primary keyword phrase 8-12 times total (Rank Math density ~1% on the exact phrase) spread across intro, 2+ H2s, body, and conclusion; secondary keywords 1-2 times each
- seo_title: 50-60 chars, starts with the primary keyword, contains a number and a power word
- slug: lowercase hyphenated, contains the primary keyword, ≤ 75 chars
- meta_description: 150-160 chars, primary keyword within first 120 chars
- Include a "Key Takeaways" bullet list near the top and at least one more list in the body
- Include the number of FAQ items specified in this blog's rules, with 15-20 word answers each
- Provide exactly 3 unique, topic-relevant CTAs (heading, description, button) and a cta_category — high-conversion, simple present tense, human-sounding, built to generate qualified leads for ${brand}
- Output ONLY valid JSON — no markdown wrappers, no extra text`;
}

// ─────────────────────────────────────────────────────────────
// CLI-based generation (primary — uses user's claude session)
// ─────────────────────────────────────────────────────────────

async function generateViaCli(systemContent, userPrompt, onProgress, cwd) {
  const model = getActiveModel();
  const effort = getActiveEffort();

  if (onProgress) onProgress(`Starting Claude CLI generation (model: ${model}, effort: ${effort})...`);

  const fullPrompt = `${systemContent}\n\n---\n\nTASK:\n${userPrompt}`;

  // Write prompt to a temp file and pipe it as stdin to avoid E2BIG
  // (Linux ARG_MAX limits command-line args to ~2MB; context files can exceed this)
  const tmpFile = path.join(os.tmpdir(), `ct-prompt-${Date.now()}.txt`);
  fs.writeFileSync(tmpFile, fullPrompt, 'utf8');

  return new Promise((resolve, reject) => {
    let stdout = '';
    let stderr = '';
    let lastProgressLen = 0;

    const args = [
      '--output-format', 'json',
      '--model', model,
      '--effort', effort,
      '--no-session-persistence',
      '--print',
    ];

    const stdinFd = fs.openSync(tmpFile, 'r');

    const proc = spawn('claude', args, {
      env: { ...process.env, NO_COLOR: '1', TERM: 'dumb', FORCE_COLOR: '0' },
      cwd: cwd || process.cwd(),
      stdio: [stdinFd, 'pipe', 'pipe'],
      shell: process.platform === 'win32', // Windows installs claude as claude.cmd
    });

    proc.stdout.on('data', (chunk) => {
      stdout += chunk.toString();
      if (onProgress && stdout.length - lastProgressLen > 300) {
        lastProgressLen = stdout.length;
        onProgress(`Claude generating... (${stdout.length} bytes received)`);
      }
    });

    proc.stderr.on('data', (chunk) => {
      stderr += chunk.toString();
    });

    proc.on('close', (code) => {
      fs.closeSync(stdinFd);
      fs.unlink(tmpFile, () => {});
      if (code !== 0) {
        return reject(new Error(stderr.trim() || `Claude CLI exited with code ${code}`));
      }
      if (onProgress) onProgress('Claude CLI finished. Parsing response...');
      resolve(stdout.trim());
    });

    proc.on('error', (err) => {
      fs.closeSync(stdinFd);
      fs.unlink(tmpFile, () => {});
      if (err.code === 'ENOENT') {
        reject(new Error('Claude CLI not found. Run "claude" in your terminal to authenticate.'));
      } else {
        reject(new Error(`Claude CLI error: ${err.message}`));
      }
    });
  });
}

/**
 * Extracts the text result from Claude CLI's JSON/JSONL output.
 *
 * With --output-format json --print, the CLI emits JSONL (one JSON object per line):
 *   {"type":"system","subtype":"init",...}
 *   {"type":"assistant","message":{...}}
 *   {"type":"result","subtype":"success","result":"...actual text...","cost_usd":...}
 *
 * We scan from the last line backwards for the result object.
 */
function extractCliResult(rawOutput) {
  // Reset per-call metrics so a missing usage block never carries over stale values
  extractCliResult._lastCostUsd = 0;
  extractCliResult._lastTokensIn = 0;
  extractCliResult._lastTokensOut = 0;

  const lines = rawOutput.trim().split('\n').filter(l => l.trim().startsWith('{'));

  // Scan from last line to first — result line is always last
  for (let i = lines.length - 1; i >= 0; i--) {
    try {
      const obj = JSON.parse(lines[i]);
      if (obj.result !== undefined && obj.result !== null) {
        const text = typeof obj.result === 'string' ? obj.result : JSON.stringify(obj.result);
        // CLI returns cost as total_cost_usd (not cost_usd)
        extractCliResult._lastCostUsd = obj.total_cost_usd || obj.cost_usd || 0;
        const u = obj.usage || {};
        extractCliResult._lastTokensIn =
          (u.input_tokens || 0) + (u.cache_creation_input_tokens || 0) + (u.cache_read_input_tokens || 0);
        extractCliResult._lastTokensOut = u.output_tokens || 0;
        return text;
      }
    } catch { /* try next line */ }
  }

  // Fallback: maybe it's a single JSON object (not JSONL)
  try {
    const wrapper = JSON.parse(rawOutput.trim());
    if (wrapper.result !== undefined) return wrapper.result || '';
  } catch { /* not JSON at all */ }

  // Last resort — return raw and let parseGeneratedContent handle it
  return rawOutput;
}

// ─────────────────────────────────────────────────────────────
// SDK-based generation (fallback if API key is set)
// ─────────────────────────────────────────────────────────────

async function generateViaSdk(systemContent, userPrompt, onProgress) {
  const client = getSdkClient();
  const model = getActiveModel();

  if (onProgress) onProgress('Starting Claude API generation...');

  let fullText = '';
  const stream = await client.messages.stream({
    model,
    max_tokens: 8192,
    system: systemContent,
    messages: [{ role: 'user', content: userPrompt }],
  });

  for await (const chunk of stream) {
    if (chunk.type === 'content_block_delta' && chunk.delta.type === 'text_delta') {
      fullText += chunk.delta.text;
      if (onProgress && fullText.length % 400 === 0) {
        onProgress(`Generating content... (${fullText.length} chars)`);
      }
    }
  }

  // Capture token usage from the final message
  generateViaSdk._lastTokensIn = 0;
  generateViaSdk._lastTokensOut = 0;
  try {
    const finalMsg = await stream.finalMessage();
    const u = finalMsg?.usage || {};
    generateViaSdk._lastTokensIn =
      (u.input_tokens || 0) + (u.cache_creation_input_tokens || 0) + (u.cache_read_input_tokens || 0);
    generateViaSdk._lastTokensOut = u.output_tokens || 0;
  } catch { /* usage unavailable — leave at 0 */ }

  return fullText;
}

// ─────────────────────────────────────────────────────────────
// Parse JSON response from Claude
// ─────────────────────────────────────────────────────────────

function slugifyKeyword(text) {
  return String(text || '')
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .split('-').slice(0, 8).join('-')
    .substring(0, 75)
    .replace(/-+$/, '');
}

// Rank Math rewards a "power word" in the SEO title.
const POWER_WORDS = ['Essential', 'Proven', 'Complete', 'Ultimate', 'Critical', 'Smart',
  'Powerful', 'Expert', 'Definitive', 'Practical', 'Key'];

// Guarantees the SEO title contains the exact focus keyword, a power word, and is <= 60 chars.
// Rank Math scores rank_math_title; if the model omitted the keyword we prepend it.
function normalizeSeoTitle(seoTitle, keyword) {
  const kw = String(keyword || '').trim();
  let t = String(seoTitle || '').trim();
  if (kw && !t.toLowerCase().includes(kw.toLowerCase())) {
    const kwTitle = kw.replace(/\b\w/g, c => c.toUpperCase());
    t = t ? `${kwTitle}: ${t}` : kwTitle;
  }
  // Ensure a power word is present (Rank Math "Title Readability" check)
  const hasPower = POWER_WORDS.some(w => new RegExp(`\\b${w}\\b`, 'i').test(t));
  if (t && !hasPower) {
    if (/:\s/.test(t)) t = t.replace(/:\s*/, ': Essential '); // insert after the "Keyword:" lead
    else t = `${t} — Essential Guide`;
  }
  if (t.length > 60) {
    t = t.slice(0, 60);
    const sp = t.lastIndexOf(' ');
    if (sp > 40) t = t.slice(0, sp);
    t = t.replace(/[\s:–—-]+$/, '');
  }
  return t;
}

// Keeps the meta description within Rank Math's 160-char limit, trimmed at a word boundary.
function normalizeMeta(meta) {
  let m = String(meta || '').trim();
  if (m.length > 160) {
    m = m.slice(0, 160);
    const sp = m.lastIndexOf(' ');
    if (sp > 140) m = m.slice(0, sp);
    m = m.replace(/[\s,;:–—-]+$/, '');
    if (!/[.!?]$/.test(m)) m += '.';
  }
  return m;
}

function parseGeneratedContent(rawText, row) {
  let text = rawText.trim();

  // Strip markdown code fences if Claude wrapped in them
  if (text.startsWith('```')) {
    text = text.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '').trim();
  }

  // Find the JSON object — scan for first { to last }
  const start = text.indexOf('{');
  const end = text.lastIndexOf('}');
  if (start !== -1 && end !== -1) {
    text = text.substring(start, end + 1);
  }

  try {
    const parsed = JSON.parse(text);
    const title = parsed.title || row.title;
    return {
      title,
      seo_title: normalizeSeoTitle(parsed.seo_title || title, row.primary_keyword),
      slug: slugifyKeyword(parsed.slug || row.primary_keyword || title),
      content: parsed.content || '',
      meta_description: normalizeMeta(parsed.meta_description || ''),
      image_prompt: parsed.image_prompt || '',
      image_alt: parsed.image_alt || row.primary_keyword || title,
      tags: Array.isArray(parsed.tags) ? parsed.tags : [],
      faq: Array.isArray(parsed.faq) ? parsed.faq : [],
      cta_category: typeof parsed.cta_category === 'string' ? parsed.cta_category.trim().toLowerCase() : 'default',
      ctas: Array.isArray(parsed.ctas)
        ? parsed.ctas.slice(0, 3).map(c => ({
            heading: String(c.heading || '').trim(),
            description: String(c.description || '').trim(),
            button: String(c.button || '').trim(),
          })).filter(c => c.heading || c.button)
        : [],
    };
  } catch (err) {
    console.warn('[claudeService] JSON parse failed:', err.message, '| raw preview:', text.substring(0, 200));

    // Attempt targeted HTML extraction from the malformed JSON.
    // This handles cases where the HTML content has unescaped quotes/newlines
    // that break JSON.parse but the HTML itself is still intact.
    const htmlStart = text.indexOf('<h1>') !== -1 ? text.indexOf('<h1>')
      : text.indexOf('<h2>') !== -1 ? text.indexOf('<h2>')
      : text.indexOf('<p>');

    if (htmlStart !== -1) {
      // Find where the HTML ends (last closing block tag before JSON suffix)
      const htmlChunk = text.substring(htmlStart);
      // Cut off any trailing JSON structure (e.g. ","tags":[...] or "})
      const trailingJson = htmlChunk.search(/",\s*"(?:tags|faq|title|meta|image)"/);
      const htmlContent = trailingJson !== -1
        ? htmlChunk.substring(0, trailingJson)
        : htmlChunk;

      // If we recovered something that looks like real HTML, use it
      if (htmlContent.length > 100 && htmlContent.includes('</')) {
        console.warn('[claudeService] JSON parse failed but HTML extracted successfully — using recovered content');
        const recoveredTitle = extractJsonField(text, 'title') || row.title;
        return {
          title: recoveredTitle,
          seo_title: extractJsonField(text, 'seo_title') || recoveredTitle,
          slug: slugifyKeyword(extractJsonField(text, 'slug') || row.primary_keyword || recoveredTitle),
          content: htmlContent.replace(/\\n/g, '\n').replace(/\\"/g, '"').replace(/\\\\/g, '\\'),
          meta_description: extractJsonField(text, 'meta_description') || '',
          image_prompt: extractJsonField(text, 'image_prompt') || '',
          image_alt: extractJsonField(text, 'image_alt') || row.primary_keyword || recoveredTitle,
          tags: [row.primary_keyword].filter(Boolean),
          faq: [],
        };
      }
    }

    // Complete failure — throw so the job is marked error and can be retried
    // rather than storing corrupted content that renders raw JSON in WordPress
    throw new Error(`Claude returned invalid JSON. Parse error: ${err.message}. Preview: ${text.substring(0, 120)}`);
  }
}

// Extract a simple string field from a JSON-like string without full parsing
function extractJsonField(text, key) {
  const keyIdx = text.indexOf(`"${key}"`);
  if (keyIdx === -1) return null;
  const colonIdx = text.indexOf(':', keyIdx);
  if (colonIdx === -1) return null;
  const quote = text.indexOf('"', colonIdx + 1);
  if (quote === -1) return null;
  let value = '';
  for (let i = quote + 1; i < text.length; i++) {
    if (text[i] === '\\') { i++; value += text[i] || ''; continue; }
    if (text[i] === '"') break;
    value += text[i];
  }
  return value || null;
}

// ─────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────

/**
 * Determines which generation mode to use.
 * Returns 'cli' or 'sdk'.
 */
async function getGenerationMode() {
  // Prefer CLI if available and authenticated
  const cliStatus = await checkCliStatus();
  if (cliStatus.installed && cliStatus.authenticated) return 'cli';
  // Fall back to SDK if API key is set
  if (process.env.ANTHROPIC_API_KEY) return 'sdk';
  throw new Error(
    'No Claude connection available. Either:\n' +
    '  1. Run "claude" in your terminal to log in (recommended)\n' +
    '  2. Set ANTHROPIC_API_KEY in your .env file'
  );
}

/**
 * Generates blog content for a single spreadsheet row.
 * @param {object} row — normalized spreadsheet row data
 * @param {string} contextPath — path to blog context folder
 * @param {string} rulesPath — path to generation rules file
 * @param {Function} onProgress — optional progress callback
 * @returns {Promise<{title, content, meta_description, image_prompt, tags, faq}>}
 */
async function generateBlogContent(row, contextPath, rulesPath, onProgress, testMode = false, feedbackList = [], additionalInstructions = '', blog = {}) {
  const brand = brandFromBlog(blog);
  // Test mode: return instant mock content — no API calls, no token usage
  if (testMode) {
    if (onProgress) onProgress('TEST MODE — generating mock content (no API call)');
    await new Promise(r => setTimeout(r, 300)); // small delay so it feels real
    const secondaryKw = Array.isArray(row.secondary_keywords) ? row.secondary_keywords : [];
    return {
      title: row.title,
      seo_title: `${row.primary_keyword} — Complete 2026 Guide`.substring(0, 60),
      slug: slugifyKeyword(row.primary_keyword || row.title),
      image_alt: `${row.primary_keyword} illustration`,
      meta_description: `[TEST] ${row.primary_keyword} — this is a test meta description for development purposes. ${row.primary_keyword} at ${brand}.`,
      content: `<h1>${row.title}</h1>
<p><strong>[TEST MODE]</strong> This is placeholder content generated without calling the Claude API. Primary keyword: <strong>${row.primary_keyword}</strong>.</p>
<h2>Section 1: Overview</h2>
<p>Test paragraph for ${row.primary_keyword}. Theme: ${row.theme || 'N/A'}. Blog type: ${row.blog_type || 'N/A'}.</p>
<h2>Section 2: Key Points</h2>
<ul>${secondaryKw.map(k => `<li>${k}</li>`).join('')}</ul>
<h2>Section 3: Target Audience</h2>
<p>${row.icp || 'Enterprise teams'} — ${row.pain_points || 'No pain points defined'}</p>
<h2>Conclusion</h2>
<p>Test conclusion for <strong>${row.title}</strong>. Replace with real content before publishing.</p>
<p><a href="https://${blog.domain || 'example.com'}/contact">Contact ${brand}</a> to learn more.</p>
<h2>FAQ</h2>
<ol>
  <li><strong>What is ${row.primary_keyword}?</strong><p>A test FAQ answer for development purposes only.</p></li>
  <li><strong>How much does ${row.primary_keyword} cost?</strong><p>Another test FAQ answer — actual content will be generated in production mode.</p></li>
  <li><strong>Why choose ${brand} for ${row.primary_keyword}?</strong><p>Test answer three — replace with real generated content.</p></li>
  <li><strong>What results can I expect from ${row.primary_keyword}?</strong><p>Test answer four — ${brand} delivers measurable outcomes.</p></li>
</ol>`,
      image_prompt: `Professional banner for article about ${row.primary_keyword}, dark tech aesthetic`,
      tags: secondaryKw.slice(0, 5),
      faq: [
        { question: `What is ${row.primary_keyword}?`, answer: `A test FAQ answer for development purposes only.` },
        { question: `How much does ${row.primary_keyword} cost?`, answer: `Test answer — actual content generated in production mode.` },
        { question: `Why choose ${brand} for ${row.primary_keyword}?`, answer: `Test answer three — replace with real generated content here.` },
        { question: `What results can I expect from ${row.primary_keyword}?`, answer: `Test answer four — ${brand} delivers measurable outcomes.` },
      ],
      cta_category: 'default',
      ctas: [
        { heading: `[TEST] Scale ${row.primary_keyword} With Confidence`, description: `Partner with ${brand} to ship faster and cut risk.`, button: `Talk to an Expert` },
        { heading: `[TEST] Get a Free ${row.primary_keyword} Assessment`, description: `See where you stand and what to fix first.`, button: `Book Your Assessment` },
        { heading: `[TEST] Build ${row.primary_keyword} That Lasts`, description: `Work with engineers who deliver production-grade results.`, button: `Start the Conversation` },
      ],
    };
  }

  // Engine switch: 'seomachine' drives seomachine's methodology + Python quality gate.
  // 'native' (default) uses the built-in 2-call pipeline below. Same return contract.
  if (getActiveEngine() === 'seomachine') {
    return await generateViaSeomachine(row, contextPath, rulesPath, onProgress, feedbackList, additionalInstructions, blog);
  }

  const contextContent = loadContextFiles(contextPath);
  const rulesContent = loadRulesFile(rulesPath);
  const systemContent = buildSystemContent(contextContent, rulesContent, feedbackList, blog);
  if (Array.isArray(feedbackList) && feedbackList.length && onProgress) {
    onProgress(`Applying ${feedbackList.length} editor feedback note${feedbackList.length !== 1 ? 's' : ''} to this generation`);
  }
  if (additionalInstructions && onProgress) {
    onProgress(`Additional instructions included in prompt`);
  }

  const mode = await getGenerationMode();
  if (onProgress) onProgress(`Using ${mode === 'cli' ? 'Claude CLI (your session)' : 'Claude API key'}...`);

  let totalCost = 0;
  let tokensIn = 0;
  let tokensOut = 0;

  // ── CALL 1: Research + Outline ──
  // A focused short prompt that produces a structured plan before writing.
  // Better quality: Claude commits to structure before writing avoids rambling.
  if (onProgress) onProgress('Call 1/2 — Researching topic and building outline...');
  const outlinePrompt = buildOutlinePrompt(row);
  let outline = null;
  try {
    let outlineRaw;
    if (mode === 'cli') {
      outlineRaw = extractCliResult(await generateViaCli(systemContent, outlinePrompt, null));
      totalCost += extractCliResult._lastCostUsd || 0;
      tokensIn += extractCliResult._lastTokensIn || 0;
      tokensOut += extractCliResult._lastTokensOut || 0;
    } else {
      outlineRaw = await generateViaSdk(systemContent, outlinePrompt, null);
      tokensIn += generateViaSdk._lastTokensIn || 0;
      tokensOut += generateViaSdk._lastTokensOut || 0;
    }
    outline = JSON.parse(outlineRaw.trim());
    if (onProgress) onProgress(`Outline ready: ${outline.h2_sections?.length || 0} sections, angle: "${outline.unique_angle?.substring(0,60)}"`);
  } catch {
    // Outline call failed — fall through to single-call generation
    if (onProgress) onProgress('Outline call failed — using single-pass generation...');
    outline = null;
  }

  // ── CALL 2: Full article using the outline as input ──
  if (onProgress) onProgress('Call 2/2 — Writing full article...');
  const userPrompt = buildUserPrompt(row, outline, additionalInstructions, blog);

  let rawText;
  if (mode === 'cli') {
    const cliOutput = await generateViaCli(systemContent, userPrompt, onProgress);
    rawText = extractCliResult(cliOutput);
    totalCost += extractCliResult._lastCostUsd || 0;
    tokensIn += extractCliResult._lastTokensIn || 0;
    tokensOut += extractCliResult._lastTokensOut || 0;
  } else {
    rawText = await generateViaSdk(systemContent, userPrompt, onProgress);
    tokensIn += generateViaSdk._lastTokensIn || 0;
    tokensOut += generateViaSdk._lastTokensOut || 0;
  }

  const result = parseGeneratedContent(rawText, row);
  result._costUsd = totalCost;
  result._tokensIn = tokensIn;
  result._tokensOut = tokensOut;
  return result;
}

/**
 * seomachine engine: single-call generation driven by seomachine's LIVE methodology
 * + the per-blog brand context, returning ct-automation's exact JSON contract, then
 * run through seomachine's Python quality gate (scrub + score). Reuses the proven
 * CLI/SDK spawn + parser so all downstream stages (posting/image/scoring) are unchanged.
 *
 * Same return shape as generateBlogContent's native path:
 *   { title, seo_title, slug, content, meta_description, image_prompt, image_alt,
 *     tags[], faq[], cta_category, ctas[], _costUsd, _tokensIn, _tokensOut }
 */
async function generateViaSeomachine(row, contextPath, rulesPath, onProgress, feedbackList = [], additionalInstructions = '', blog = {}) {
  const seomachine = require('./seomachineService');
  const root = seomachine.resolveRoot();

  const methodology = seomachine.loadMethodology(root);   // LIVE upstream write.md
  if (onProgress) {
    onProgress(methodology
      ? `Engine: seomachine — using live methodology from ${root}`
      : `Engine: seomachine — write.md not found at ${root} (proceeding with brand context only)`);
  }

  const contextContent = loadContextFiles(contextPath);   // per-blog brand context (reused)
  const rulesContent = loadRulesFile(rulesPath);          // per-blog rules (reused)
  const feedbackSection = buildFeedbackSection(feedbackList);
  const brand = brandFromBlog(blog);

  const systemContent = seomachine.buildSystemContent({ methodology, contextContent, rulesContent, feedbackSection, brand });
  const userPrompt = seomachine.buildUserPrompt({ row, additionalInstructions });

  if (Array.isArray(feedbackList) && feedbackList.length && onProgress) {
    onProgress(`Applying ${feedbackList.length} editor feedback note${feedbackList.length !== 1 ? 's' : ''} to this generation`);
  }

  const mode = await getGenerationMode();
  if (onProgress) onProgress(`Generating via ${mode === 'cli' ? 'Claude CLI (your session)' : 'Claude API key'} — ${brand} (seomachine pipeline)...`);

  let totalCost = 0, tokensIn = 0, tokensOut = 0, rawText;
  if (mode === 'cli') {
    // Run with cwd = seomachine root so Claude Code's ambient project context aligns
    // with seomachine (its CLAUDE.md/.claude), reinforcing the injected methodology.
    const cliOutput = await generateViaCli(systemContent, userPrompt, onProgress, root);
    rawText = extractCliResult(cliOutput);
    totalCost += extractCliResult._lastCostUsd || 0;
    tokensIn += extractCliResult._lastTokensIn || 0;
    tokensOut += extractCliResult._lastTokensOut || 0;
  } else {
    rawText = await generateViaSdk(systemContent, userPrompt, onProgress);
    tokensIn += generateViaSdk._lastTokensIn || 0;
    tokensOut += generateViaSdk._lastTokensOut || 0;
  }

  const result = parseGeneratedContent(rawText, row);

  // Quality gate — scrub AI watermarks + score (best-effort; never fails generation)
  try {
    const gate = await seomachine.runQualityGate(result.content, { root, onProgress });
    if (gate.ok) {
      if (gate.cleaned && gate.cleaned !== result.content) {
        result.content = gate.cleaned;
        if (onProgress && gate.scrubber_changed) onProgress('Scrubbed AI-watermark characters / telltale phrasing from content');
      }
      if (gate.composite_score != null) {
        result._seoMachineScore = gate.composite_score;
        result._seoMachineDimensions = gate.dimensions || null;
        if (onProgress) onProgress(`seomachine quality score: ${gate.composite_score}/100`);
      }
    } else if (onProgress) {
      onProgress(`seomachine quality gate skipped (non-fatal): ${gate.error || 'unavailable'}`);
    }
  } catch (e) {
    if (onProgress) onProgress(`Quality gate error (non-fatal): ${e.message}`);
  }

  result._costUsd = totalCost;
  result._tokensIn = tokensIn;
  result._tokensOut = tokensOut;
  return result;
}

/**
 * Tests the active Claude connection (CLI or SDK).
 * Returns { ok, mode, model?, error? }
 */
async function testConnection() {
  const cliStatus = await checkCliStatus();

  if (cliStatus.installed && cliStatus.authenticated) {
    // Test CLI
    try {
      const model = getActiveModel();
      const result = await execClaudeAsync([
        '-p', 'Reply with exactly: OK',
        '--output-format', 'json',
        '--model', model,
        '--no-session-persistence',
      ], {
        timeout: 60000,
      });
      const raw = extractCliResult(result.stdout.trim());
      return { ok: true, mode: 'cli', model, response: raw.replace(/["`\n]/g, '').substring(0, 50) };
    } catch (err) {
      return { ok: false, mode: 'cli', error: err.message };
    }
  }

  if (process.env.ANTHROPIC_API_KEY) {
    try {
      const client = getSdkClient();
      const model = getActiveModel();
      const response = await client.messages.create({
        model,
        max_tokens: 20,
        messages: [{ role: 'user', content: 'Reply with just "OK"' }],
      });
      return { ok: true, mode: 'sdk', model, response: response.content[0]?.text?.trim() };
    } catch (err) {
      return { ok: false, mode: 'sdk', error: err.message };
    }
  }

  return { ok: false, mode: 'none', error: 'No Claude connection configured. Login via terminal or set API key.' };
}

/**
 * Checks Claude CLI installation and auth status.
 * Result is cached for 5 minutes to avoid slow re-checks on every HTTP request.
 * Call invalidateCLiCache() after a user explicitly re-authenticates.
 * Returns { installed, authenticated, version? }
 */
async function checkCliStatus() {
  const now = Date.now();
  if (_cliCache && now - _cliCacheTime < CLI_CACHE_TTL) {
    return _cliCache;
  }

  const result = { installed: false, authenticated: false };
  try {
    const { stdout } = await execClaudeAsync(['--version'], { timeout: 5000 });
    result.installed = true;
    result.version = stdout.trim();
  } catch {
    _cliCache = result;
    _cliCacheTime = now;
    return result;
  }

  // Quick auth check — run a minimal prompt
  try {
    await execClaudeAsync([
      '-p', 'Hi',
      '--output-format', 'json',
      '--no-session-persistence',
    ], {
      timeout: 30000,
    });
    result.authenticated = true;
  } catch {
    result.authenticated = false;
  }

  _cliCache = result;
  _cliCacheTime = now;
  return result;
}

function invalidateCliCache() {
  _cliCache = null;
  _cliCacheTime = 0;
}

/**
 * Runs a Claude CLI command and streams output lines via a callback.
 * Used by the terminal panel in claude-setup page.
 * @param {string} promptText — the prompt to send
 * @param {Function} onLine — called with each line of output
 * @param {Function} onDone — called when process exits
 */
function streamCliOutput(promptText, onLine, onDone) {
  const model = getActiveModel();
  const args = [
    '-p', promptText,
    '--output-format', 'stream-json',
    '--model', model,
    '--no-session-persistence',
  ];

  onLine({ type: 'cmd', text: `$ claude -p "${promptText.substring(0, 60)}..." --output-format stream-json` });

  const proc = spawn('claude', args, {
    env: { ...process.env, NO_COLOR: '1', TERM: 'dumb' },
    cwd: process.cwd(),
    shell: process.platform === 'win32',
  });

  let buffer = '';
  proc.stdout.on('data', (chunk) => {
    buffer += chunk.toString();
    const lines = buffer.split('\n');
    buffer = lines.pop(); // keep incomplete line
    for (const line of lines) {
      if (!line.trim()) continue;
      try {
        const event = JSON.parse(line);
        // Stream-json events: system, assistant, result
        if (event.type === 'assistant' && event.message?.content) {
          for (const block of event.message.content) {
            if (block.type === 'text') {
              onLine({ type: 'output', text: block.text });
            }
          }
        } else if (event.type === 'result') {
          onLine({ type: 'info', text: `Done. Cost: $${(event.cost_usd || 0).toFixed(4)}` });
        }
      } catch {
        onLine({ type: 'output', text: line });
      }
    }
  });

  proc.stderr.on('data', (chunk) => {
    onLine({ type: 'err', text: chunk.toString().trim() });
  });

  proc.on('close', (code) => {
    onDone(code);
  });

  proc.on('error', (err) => {
    if (err.code === 'ENOENT') {
      onLine({ type: 'err', text: 'Claude CLI not found. Install it with: npm install -g @anthropic-ai/claude-code' });
    } else {
      onLine({ type: 'err', text: err.message });
    }
    onDone(1);
  });

  return proc;
}

// ─────────────────────────────────────────────────────────────
// Claude usage / balance tracking (OAuth subscription session)
// ─────────────────────────────────────────────────────────────

function readOAuthCredentials() {
  try {
    const p = path.join(os.homedir(), '.claude', '.credentials.json');
    const data = JSON.parse(fs.readFileSync(p, 'utf8'));
    return data.claudeAiOauth || null;
  } catch {
    return null;
  }
}

// Caches to avoid hammering the rate-limited OAuth endpoints (Anthropic 429s aggressively).
let _usageCache = { data: null, time: 0 };
let _profileCache = { data: null, time: 0 };
const USAGE_TTL = 60 * 1000;          // serve cached usage for 60s
const PROFILE_TTL = 30 * 60 * 1000;   // profile barely changes — cache 30 min

/**
 * Fetches the user's live Claude usage limits (session + weekly) using the
 * local Claude CLI OAuth token. Only works in CLI (subscription) mode — API
 * key accounts have no equivalent public usage endpoint.
 *
 * Results are cached for 60s and, on rate-limit/transient errors, the last
 * good snapshot is returned with `stale: true` so the UI never shows a 429.
 */
async function getClaudeUsage() {
  const oauth = readOAuthCredentials();
  if (!oauth || !oauth.accessToken) {
    return { available: false, reason: 'No Claude CLI login found. Run `claude` to sign in, then refresh.' };
  }
  if (oauth.expiresAt && Date.now() > oauth.expiresAt) {
    return {
      available: false,
      reason: 'Claude session token expired. Run any `claude` command to refresh it.',
      subscription: oauth.subscriptionType || null,
    };
  }

  // Fresh cache — return immediately, no API call (dedupes multiple tabs/loads)
  if (_usageCache.data && Date.now() - _usageCache.time < USAGE_TTL) {
    return { ..._usageCache.data, cached: true };
  }

  const axios = require('axios');
  const base = (process.env.ANTHROPIC_BASE_URL || 'https://api.anthropic.com').replace(/\/$/, '');
  const headers = {
    Authorization: `Bearer ${oauth.accessToken}`,
    'anthropic-beta': 'oauth-2025-04-20',
    'Content-Type': 'application/json',
  };

  // Reuse cached profile when possible — cuts the request count in half
  let profile = (_profileCache.data && Date.now() - _profileCache.time < PROFILE_TTL)
    ? _profileCache.data
    : null;

  try {
    const calls = [axios.get(`${base}/api/oauth/usage`, { headers, timeout: 10000 })];
    if (!profile) calls.push(axios.get(`${base}/api/oauth/profile`, { headers, timeout: 10000 }));
    const results = await Promise.allSettled(calls);
    const usageRes = results[0];

    if (usageRes.status !== 'fulfilled') {
      const code = usageRes.reason?.response?.status;
      // Fall back to the last good snapshot on rate-limit / transient errors
      if (_usageCache.data) {
        return {
          ..._usageCache.data,
          stale: true,
          reason: code === 429 ? 'Claude usage API is rate-limiting refreshes — showing recent data.' : undefined,
        };
      }
      return {
        available: false,
        reason: code === 429
          ? 'Claude usage API is busy (rate limited). It will update automatically in a minute.'
          : code === 401
          ? 'Claude session unauthorized — run `claude` to refresh your login.'
          : `Could not fetch usage (${code || usageRes.reason?.message || 'network error'}).`,
      };
    }

    if (!profile && results[1]?.status === 'fulfilled') {
      profile = results[1].value.data;
      _profileCache = { data: profile, time: Date.now() };
    }

    const u = usageRes.value.data || {};
    const data = {
      available: true,
      subscription: oauth.subscriptionType || null,
      rate_limit_tier: oauth.rateLimitTier || null,
      account: profile?.account
        ? { name: profile.account.display_name || profile.account.full_name, email: profile.account.email }
        : null,
      organization: profile?.organization
        ? { name: profile.organization.name, type: profile.organization.organization_type }
        : null,
      five_hour: u.five_hour || null,
      seven_day: u.seven_day || null,
      seven_day_opus: u.seven_day_opus || null,
      extra_usage: u.extra_usage || null,
      fetched_at: new Date().toISOString(),
    };
    _usageCache = { data, time: Date.now() };
    return data;
  } catch (err) {
    if (_usageCache.data) return { ..._usageCache.data, stale: true };
    return { available: false, reason: err.message };
  }
}

// ─────────────────────────────────────────────────────────────
// Usage-limit detection & auto-resume support
// ─────────────────────────────────────────────────────────────

// Phrases a Claude usage/rate limit surfaces with (CLI or SDK).
const USAGE_LIMIT_RE = /usage limit|limit reached|rate.?limit|too many requests|\b429\b|quota|insufficient (credit|quota)|out of (credit|usage)|overloaded/i;

function isUsageLimitError(message) {
  return USAGE_LIMIT_RE.test(String(message || ''));
}

/**
 * Decides whether a generation error is a Claude usage/limit condition and, if so,
 * when the limit resets (epoch ms). Combines the error text with live usage data so
 * it also catches the vague "Claude CLI exited with code 1" case — a true limit shows
 * up as a maxed usage window even when the CLI prints no message.
 * @returns {Promise<{limited: boolean, resetAt: number|null}>}
 */
async function detectUsageLimit(err) {
  const msg = String((err && err.message) || err || '');
  let limited = isUsageLimitError(msg);
  let resetAt = null;

  try {
    const u = await getClaudeUsage();
    if (u && u.available !== false) {
      const futureTs = (w) => {
        const t = w && w.resets_at ? new Date(w.resets_at).getTime() : NaN;
        return isFinite(t) && t > Date.now() ? t : null;
      };
      const wins = [u.five_hour, u.seven_day, u.seven_day_opus].filter(Boolean);
      const maxed = wins.filter(w => (w.utilization || 0) >= 99 && futureTs(w));
      if (maxed.length) {
        limited = true;                                   // a window is exhausted → definitely limited
        resetAt = Math.min(...maxed.map(futureTs));
      } else if (limited) {
        const ts = wins.map(futureTs).filter(Boolean);    // message says limit; use soonest known reset
        if (ts.length) resetAt = Math.min(...ts);
      }
    }
  } catch { /* usage API unavailable — fall back to message-only detection */ }

  return { limited, resetAt };
}

module.exports = {
  generateBlogContent,
  isUsageLimitError,
  detectUsageLimit,
  testConnection,
  checkCliStatus,
  invalidateCliCache,
  streamCliOutput,
  loadContextFiles,
  getGenerationMode,
  getClaudeUsage,
  normalizeSeoTitle,
  normalizeMeta,
  readOAuthCredentials,
};
